
package com.lain.soapmuestra.source;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "productoService", targetNamespace = "http://source.SoapMuestra.lain.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ProductoService {


    /**
     * 
     * @param precio
     * @param id
     * @param cantidad
     * @param nombre
     * @return
     *     returns com.lain.soapmuestra.source.Type
     */
    @WebMethod
    @WebResult(name = "Rtdo", targetNamespace = "")
    @RequestWrapper(localName = "createProducto", targetNamespace = "http://source.SoapMuestra.lain.com/", className = "com.lain.soapmuestra.source.CreateProducto")
    @ResponseWrapper(localName = "createProductoResponse", targetNamespace = "http://source.SoapMuestra.lain.com/", className = "com.lain.soapmuestra.source.CreateProductoResponse")
    @Action(input = "http://source.SoapMuestra.lain.com/productoService/createProductoRequest", output = "http://source.SoapMuestra.lain.com/productoService/createProductoResponse")
    public Type createProducto(
        @WebParam(name = "nombre", targetNamespace = "")
        String nombre,
        @WebParam(name = "id", targetNamespace = "")
        int id,
        @WebParam(name = "cantidad", targetNamespace = "")
        int cantidad,
        @WebParam(name = "precio", targetNamespace = "")
        double precio);

    /**
     * 
     * @param serviceparam
     * @return
     *     returns com.lain.soapmuestra.source.Type
     */
    @WebMethod
    @WebResult(name = "Rtdo", targetNamespace = "")
    @RequestWrapper(localName = "readProducto", targetNamespace = "http://source.SoapMuestra.lain.com/", className = "com.lain.soapmuestra.source.ReadProducto")
    @ResponseWrapper(localName = "readProductoResponse", targetNamespace = "http://source.SoapMuestra.lain.com/", className = "com.lain.soapmuestra.source.ReadProductoResponse")
    @Action(input = "http://source.SoapMuestra.lain.com/productoService/readProductoRequest", output = "http://source.SoapMuestra.lain.com/productoService/readProductoResponse")
    public Type readProducto(
        @WebParam(name = "serviceparam", targetNamespace = "")
        int serviceparam);

    /**
     * 
     * @param nombretoupdate
     * @param cantidadtoupdate
     * @param idtoupdate
     * @param preciotoupdate
     * @return
     *     returns com.lain.soapmuestra.source.Type
     */
    @WebMethod
    @WebResult(name = "Rtdo", targetNamespace = "")
    @RequestWrapper(localName = "updateProducto", targetNamespace = "http://source.SoapMuestra.lain.com/", className = "com.lain.soapmuestra.source.UpdateProducto")
    @ResponseWrapper(localName = "updateProductoResponse", targetNamespace = "http://source.SoapMuestra.lain.com/", className = "com.lain.soapmuestra.source.UpdateProductoResponse")
    @Action(input = "http://source.SoapMuestra.lain.com/productoService/updateProductoRequest", output = "http://source.SoapMuestra.lain.com/productoService/updateProductoResponse")
    public Type updateProducto(
        @WebParam(name = "nombretoupdate", targetNamespace = "")
        String nombretoupdate,
        @WebParam(name = "idtoupdate", targetNamespace = "")
        int idtoupdate,
        @WebParam(name = "cantidadtoupdate", targetNamespace = "")
        int cantidadtoupdate,
        @WebParam(name = "preciotoupdate", targetNamespace = "")
        double preciotoupdate);

    /**
     * 
     * @param serviceparam
     * @return
     *     returns com.lain.soapmuestra.source.Type
     */
    @WebMethod
    @WebResult(name = "Rtdo", targetNamespace = "")
    @RequestWrapper(localName = "deleteProducto", targetNamespace = "http://source.SoapMuestra.lain.com/", className = "com.lain.soapmuestra.source.DeleteProducto")
    @ResponseWrapper(localName = "deleteProductoResponse", targetNamespace = "http://source.SoapMuestra.lain.com/", className = "com.lain.soapmuestra.source.DeleteProductoResponse")
    @Action(input = "http://source.SoapMuestra.lain.com/productoService/deleteProductoRequest", output = "http://source.SoapMuestra.lain.com/productoService/deleteProductoResponse")
    public Type deleteProducto(
        @WebParam(name = "serviceparam", targetNamespace = "")
        int serviceparam);

    /**
     * 
     * @return
     *     returns java.util.List<com.lain.soapmuestra.source.Type>
     */
    @WebMethod
    @WebResult(name = "Rtdo", targetNamespace = "")
    @RequestWrapper(localName = "getListaProducto", targetNamespace = "http://source.SoapMuestra.lain.com/", className = "com.lain.soapmuestra.source.GetListaProducto")
    @ResponseWrapper(localName = "getListaProductoResponse", targetNamespace = "http://source.SoapMuestra.lain.com/", className = "com.lain.soapmuestra.source.GetListaProductoResponse")
    @Action(input = "http://source.SoapMuestra.lain.com/productoService/getListaProductoRequest", output = "http://source.SoapMuestra.lain.com/productoService/getListaProductoResponse")
    public List<Type> getListaProducto();

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "Rtdo", targetNamespace = "")
    @RequestWrapper(localName = "clearListaProducto", targetNamespace = "http://source.SoapMuestra.lain.com/", className = "com.lain.soapmuestra.source.ClearListaProducto")
    @ResponseWrapper(localName = "clearListaProductoResponse", targetNamespace = "http://source.SoapMuestra.lain.com/", className = "com.lain.soapmuestra.source.ClearListaProductoResponse")
    @Action(input = "http://source.SoapMuestra.lain.com/productoService/clearListaProductoRequest", output = "http://source.SoapMuestra.lain.com/productoService/clearListaProductoResponse")
    public String clearListaProducto();

}
